# Generated by Django 2.1.3 on 2018-11-17 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jed',
            fields=[
                ('id_jed', models.IntegerField(primary_key=True, serialize=False)),
                ('ime_jedi', models.CharField(max_length=256)),
                ('cena', models.FloatField()),
                ('opis', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'jed',
            },
        ),
        migrations.CreateModel(
            name='JedilniList',
            fields=[
                ('id_jedilni_list', models.IntegerField(primary_key=True, serialize=False)),
                ('vrsta', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'jedilni_list',
            },
        ),
        migrations.CreateModel(
            name='Narocilo',
            fields=[
                ('id_narocila', models.IntegerField(primary_key=True, serialize=False)),
                ('cas_prevzema', models.TimeField()),
            ],
            options={
                'db_table': 'narocilo',
            },
        ),
        migrations.CreateModel(
            name='Naslov',
            fields=[
                ('id_naslov', models.IntegerField(primary_key=True, serialize=False)),
                ('ulica', models.CharField(max_length=256)),
                ('hisna_stevilka', models.IntegerField()),
            ],
            options={
                'db_table': 'naslov',
            },
        ),
        migrations.CreateModel(
            name='Posta',
            fields=[
                ('postna_stevilka', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('kraj', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'posta',
            },
        ),
        migrations.CreateModel(
            name='Restavracija',
            fields=[
                ('id_restavracija', models.IntegerField(primary_key=True, serialize=False)),
                ('ime_restavracije', models.CharField(max_length=256)),
                ('ocena', models.FloatField()),
            ],
            options={
                'db_table': 'restavracija',
            },
        ),
        migrations.CreateModel(
            name='Sestavine',
            fields=[
                ('id_sestavine', models.IntegerField(primary_key=True, serialize=False)),
                ('ime_sestavine', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'sestavine',
            },
        ),
        migrations.CreateModel(
            name='TipRestavracije',
            fields=[
                ('id_tip_restavracije', models.IntegerField(primary_key=True, serialize=False)),
                ('tip', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'tip_restavracije',
            },
        ),
        migrations.CreateModel(
            name='Uporabnik',
            fields=[
                ('id_uporabnik', models.IntegerField(primary_key=True, serialize=False)),
                ('e_mail', models.CharField(db_column='E-mail', max_length=256)),
                ('geslo', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'uporabnik',
            },
        ),
        migrations.CreateModel(
            name='Vloga',
            fields=[
                ('id_vloga', models.IntegerField(primary_key=True, serialize=False)),
                ('ime_vloga', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'vloga',
            },
        ),
        migrations.CreateModel(
            name='JediNarocila',
            fields=[
                ('id_jed', models.ForeignKey(db_column='id_jed', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ServeUp.Jed')),
            ],
            options={
                'db_table': 'jedi_narocila',
            },
        ),
        migrations.CreateModel(
            name='Upravlja',
            fields=[
                ('id_restavracija', models.ForeignKey(db_column='id_restavracija', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ServeUp.Restavracija')),
            ],
            options={
                'db_table': 'upravlja',
            },
        ),
        migrations.CreateModel(
            name='Vsebuje',
            fields=[
                ('id_jed', models.ForeignKey(db_column='id_jed', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ServeUp.Jed')),
                ('id_sestavine', models.ForeignKey(db_column='id_sestavine', on_delete=django.db.models.deletion.DO_NOTHING, to='ServeUp.Sestavine')),
            ],
            options={
                'db_table': 'vsebuje',
            },
        ),
        migrations.AddField(
            model_name='uporabnik',
            name='id_vloga',
            field=models.ForeignKey(db_column='id_vloga', on_delete=django.db.models.deletion.DO_NOTHING, to='ServeUp.Vloga'),
        ),
        migrations.AddField(
            model_name='restavracija',
            name='id_naslov',
            field=models.ForeignKey(db_column='id_naslov', on_delete=django.db.models.deletion.DO_NOTHING, to='ServeUp.Naslov'),
        ),
        migrations.AddField(
            model_name='restavracija',
            name='id_tip_restavracije',
            field=models.ForeignKey(db_column='id_tip_restavracije', on_delete=django.db.models.deletion.DO_NOTHING, to='ServeUp.TipRestavracije'),
        ),
        migrations.AddField(
            model_name='naslov',
            name='postna_stevilka',
            field=models.ForeignKey(db_column='postna_stevilka', on_delete=django.db.models.deletion.DO_NOTHING, to='ServeUp.Posta'),
        ),
        migrations.AddField(
            model_name='narocilo',
            name='id_restavracija',
            field=models.ForeignKey(db_column='id_restavracija', on_delete=django.db.models.deletion.DO_NOTHING, to='ServeUp.Restavracija'),
        ),
        migrations.AddField(
            model_name='narocilo',
            name='id_uporabnik',
            field=models.ForeignKey(db_column='id_uporabnik', on_delete=django.db.models.deletion.DO_NOTHING, to='ServeUp.Uporabnik'),
        ),
        migrations.AddField(
            model_name='jed',
            name='id_jedilni_list',
            field=models.ForeignKey(db_column='id_jedilni_list', on_delete=django.db.models.deletion.DO_NOTHING, to='ServeUp.JedilniList'),
        ),
        migrations.AddField(
            model_name='jed',
            name='id_restavracija',
            field=models.ForeignKey(blank=True, db_column='id_restavracija', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ServeUp.Restavracija'),
        ),
        migrations.AddField(
            model_name='upravlja',
            name='id_uporabnik',
            field=models.ForeignKey(db_column='id_uporabnik', on_delete=django.db.models.deletion.DO_NOTHING, to='ServeUp.Uporabnik'),
        ),
        migrations.AddField(
            model_name='jedinarocila',
            name='id_narocila',
            field=models.ForeignKey(db_column='id_narocila', on_delete=django.db.models.deletion.DO_NOTHING, to='ServeUp.Narocilo'),
        ),
        migrations.AlterUniqueTogether(
            name='vsebuje',
            unique_together={('id_jed', 'id_sestavine')},
        ),
        migrations.AlterUniqueTogether(
            name='upravlja',
            unique_together={('id_restavracija', 'id_uporabnik')},
        ),
        migrations.AlterUniqueTogether(
            name='jedinarocila',
            unique_together={('id_jed', 'id_narocila')},
        ),
    ]
