# Generated by Django 2.1.3 on 2018-11-22 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUporabnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
            ],
            options={
                'db_table': 'admin_uporabnik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jed',
            fields=[
                ('id_jed', models.AutoField(primary_key=True, serialize=False)),
                ('ime_jedi', models.TextField()),
                ('cena', models.FloatField()),
                ('opis', models.TextField()),
            ],
            options={
                'db_table': 'jed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JedilniList',
            fields=[
                ('id_jedilni_list', models.AutoField(primary_key=True, serialize=False)),
                ('vrsta', models.TextField()),
            ],
            options={
                'db_table': 'jedilni_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Narocilo',
            fields=[
                ('id_narocila', models.AutoField(primary_key=True, serialize=False)),
                ('cas_prevzema', models.TimeField()),
            ],
            options={
                'db_table': 'narocilo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Naslov',
            fields=[
                ('id_naslov', models.AutoField(primary_key=True, serialize=False)),
                ('ulica', models.TextField()),
                ('hisna_stevilka', models.IntegerField()),
            ],
            options={
                'db_table': 'naslov',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Posta',
            fields=[
                ('postna_stevilka', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('kraj', models.TextField()),
            ],
            options={
                'db_table': 'posta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restavracija',
            fields=[
                ('id_restavracija', models.AutoField(primary_key=True, serialize=False)),
                ('ime_restavracije', models.TextField()),
                ('ocena', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'restavracija',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sestavine',
            fields=[
                ('id_sestavine', models.AutoField(primary_key=True, serialize=False)),
                ('ime_sestavine', models.TextField()),
            ],
            options={
                'db_table': 'sestavine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipRestavracije',
            fields=[
                ('id_tip_restavracije', models.AutoField(primary_key=True, serialize=False)),
                ('tip', models.TextField()),
            ],
            options={
                'db_table': 'tip_restavracije',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uporabnik',
            fields=[
                ('id_uporabnik', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'uporabnik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JediNarocila',
            fields=[
                ('id_jed', models.ForeignKey(db_column='id_jed', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ServeUp.Jed')),
            ],
            options={
                'db_table': 'jedi_narocila',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vsebuje',
            fields=[
                ('id_jed', models.ForeignKey(db_column='id_jed', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ServeUp.Jed')),
            ],
            options={
                'db_table': 'vsebuje',
                'managed': False,
            },
        ),
    ]
