# Generated by Django 2.1.3 on 2018-11-19 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServeUp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jed',
            name='ime_jedi',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jed',
            name='opis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jedilnilist',
            name='vrsta',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jedinarocila',
            name='id_jed',
            field=models.OneToOneField(db_column='id_jed', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ServeUp.Jed'),
        ),
        migrations.AlterField(
            model_name='naslov',
            name='ulica',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posta',
            name='kraj',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='restavracija',
            name='ime_restavracije',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sestavine',
            name='ime_sestavine',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tiprestavracije',
            name='tip',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='e_mail',
            field=models.TextField(db_column='E-mail'),
        ),
        migrations.AlterField(
            model_name='uporabnik',
            name='geslo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='upravlja',
            name='id_restavracija',
            field=models.OneToOneField(db_column='id_restavracija', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ServeUp.Restavracija'),
        ),
        migrations.AlterField(
            model_name='vloga',
            name='ime_vloga',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vsebuje',
            name='id_jed',
            field=models.OneToOneField(db_column='id_jed', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ServeUp.Jed'),
        ),
    ]
