# Generated by Django 2.1.3 on 2018-11-19 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServeUp', '0002_auto_20181119_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jed',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jedilnilist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jedinarocila',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='narocilo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='naslov',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='posta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='restavracija',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sestavine',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tiprestavracije',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='uporabnik',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='upravlja',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='vloga',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='vsebuje',
            options={'managed': False},
        ),
    ]
